# Generated by Django 3.1 on 2020-08-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race_main', '0003_auto_20200824_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingame',
            old_name='player1_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ingame',
            name='player2_name',
        ),
        migrations.RemoveField(
            model_name='ingame',
            name='player3_name',
        ),
        migrations.RemoveField(
            model_name='ingame',
            name='player4_name',
        ),
    ]
